Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
      d.build_dir = "."
      d.create_args = [
        "--privileged",
        "-v", "/sys/fs/cgroup:/sys/fs/cgroup:rw",
        "--cgroupns=host"
      ]
      d.has_ssh = true
      d.remains_running = true
    end
  
    config.vm.synced_folder ".", "/vagrant", disabled: true
    
    config.ssh.username = "root"
    config.ssh.password = "vagrant"
    config.ssh.insert_key = false
    config.ssh.forward_agent = true
    config.ssh.keys_only = false
end